import { Sensitivity, zeroSensitivity } from "./ActorSexualStatus/Sensitivity";
import { partIds } from "./partIds";
import { ExtraExercises, Exercises, ExtraExercisePart } from "./Exercises";

const extraExercisesCoefficient: {
    [K in keyof ExtraExercises]: Partial<Sensitivity>;
} = {
    head: {
        skin: 0.05,
        brain: 0.1,
        ear: 0.2,
        mouth: 0.2,
        tongue: 0.2,
        throat: 0.1,
        bust: 0.4,
        nipple: 0.4,
        arm: 0.4,
        armpit: 0.1,
        stomach: 0.2,
        back: 0.1,
    },
    speak: {
        mouth: 0.8,
        tongue: 1,
        throat: 1,
    },
    upper: {
        skin: 0.05,
        brain: 0.1,
        ear: 0.2,
        mouth: 0.2,
        tongue: 0.2,
        throat: 0.2,
        bust: 1,
        nipple: 1,
        hand: 1,
        arm: 1,
        armpit: 0.5,
        stomach: 1,
        back: 0.5,
        clitoris: 0,
        urethra: 0.2,
        bladder: 0.8,
        labia: 0,
        vagina: 0,
        portio: 0.8,
        womb: 0.8,
        ovary: 0.8,
        anus: 0,
        intestine: 0.5,
        hip: 0.5,
        thigh: 0.3,
        leg: 0.3,
        foot: 0.3,
    },
    chest: {
        skin: 0.05,
        brain: 0.05,
        ear: 0,
        mouth: 0.2,
        tongue: 0.2,
        throat: 0.2,
        bust: 1,
        nipple: 1,
        hand: 0,
        arm: 1,
        armpit: 1,
        stomach: 0.8,
        back: 0.7,
        clitoris: 0,
        urethra: 0,
        bladder: 0.3,
        labia: 0,
        vagina: 0,
        portio: 0,
        womb: 0,
        ovary: 0,
        anus: 0,
        intestine: 0,
        hip: 0,
        thigh: 0,
        leg: 0,
        foot: 0,
    },
    abdominal: {
        skin: 0.05,
        brain: 0.1,
        ear: 0,
        mouth: 0.2,
        tongue: 0.2,
        throat: 0.2,
        bust: 0.9,
        nipple: 0.8,
        hand: 0,
        arm: 0.5,
        armpit: 0,
        stomach: 1,
        back: 0.8,
        clitoris: 0,
        urethra: 0.3,
        bladder: 1,
        labia: 0,
        vagina: 0.3,
        portio: 1,
        womb: 1,
        ovary: 1,
        anus: 0.1,
        intestine: 1,
        hip: 0.4,
        thigh: 0,
        leg: 0,
        foot: 0,
    },
    waist: {
        skin: 0.05,
        brain: 0,
        ear: 0,
        mouth: 0,
        tongue: 0,
        throat: 0,
        bust: 0.6,
        nipple: 0.6,
        hand: 0,
        arm: 0,
        armpit: 0,
        stomach: 0.8,
        back: 0.2,
        clitoris: 0.4,
        urethra: 1,
        bladder: 1,
        labia: 0.3,
        vagina: 1,
        portio: 1,
        womb: 1,
        ovary: 1,
        anus: 0.3,
        intestine: 1,
        hip: 1,
        thigh: 0.5,
        leg: 0,
        foot: 0,
    },
    crotch: {
        skin: 0.05,
        brain: 0,
        ear: 0,
        mouth: 0,
        tongue: 0,
        throat: 0,
        bust: 0,
        nipple: 0,
        hand: 0,
        arm: 0,
        stomach: 0.2,
        clitoris: 1,
        urethra: 1,
        bladder: 0.5,
        labia: 1,
        vagina: 0.8,
        portio: 0.5,
        womb: 0.5,
        ovary: 0.3,
        anus: 1,
        intestine: 0.5,
        hip: 0.5,
        thigh: 1,
        leg: 0.5,
        foot: 0,
    },
    lower: {
        skin: 0.05,
        brain: 0,
        ear: 0,
        mouth: 0,
        tongue: 0,
        throat: 0,
        bust: 0.4,
        nipple: 0.4,
        hand: 0,
        arm: 0,
        armpit: 0,
        stomach: 0,
        back: 0,
        clitoris: 0.5,
        urethra: 0.3,
        bladder: 0.6,
        labia: 0.2,
        vagina: 0.3,
        portio: 0.2,
        womb: 0.3,
        ovary: 0.3,
        anus: 1,
        intestine: 1,
        hip: 1,
        thigh: 1,
        leg: 1,
        foot: 1,
    },
    rear: {
        skin: 0.05,
        brain: 0,
        ear: 0,
        mouth: 0.1,
        tongue: 0.1,
        throat: 0.1,
        bust: 0.8,
        nipple: 0.5,
        hand: 0,
        arm: 0.2,
        armpit: 0.1,
        stomach: 0.3,
        back: 1,
        clitoris: 0,
        urethra: 0,
        bladder: 0.2,
        labia: 0,
        vagina: 0.1,
        portio: 0.1,
        womb: 0.2,
        ovary: 0.2,
        anus: 0.1,
        intestine: 0.5,
        hip: 1,
        thigh: 0,
        leg: 0,
        foot: 0,
    },
    magic: {
        skin: 0.1,
        brain: 0.1,
        ear: 0.1,
        mouth: 0.1,
        tongue: 0.1,
        throat: 0.1,
        bust: 0.3,
        nipple: 0.5,
        hand: 0.1,
        arm: 0.1,
        armpit: 0.1,
        stomach: 0.1,
        back: 0.1,
        clitoris: 0.5,
        urethra: 0.3,
        bladder: 0.3,
        labia: 0.5,
        vagina: 0.5,
        portio: 0.5,
        womb: 0.5,
        ovary: 0.5,
        anus: 0.1,
        intestine: 0.1,
        hip: 0.1,
        thigh: 0.1,
        leg: 0.1,
        foot: 0.1,
    },
};

const extraExercisesKey = Object.keys(extraExercisesCoefficient) as ExtraExercisePart[];

export function canonicalExercise(exercises: Exercises): Sensitivity {
    const canon = { ...zeroSensitivity };
    for (const extraKey of extraExercisesKey) {
        const extraExercise = exercises[extraKey];
        if (extraExercise) {
            const extra = extraExercisesCoefficient[extraKey];
            for (const partId of partIds) {
                const coefficient = extra[partId];
                if (coefficient) canon[partId] += coefficient * extraExercise;
            }
        }
    }
    for (const partId of partIds) {
        const exercise = exercises[partId];
        if (exercise) canon[partId] += exercise;
    }
    return canon;
}
